name: "Push Docker Image"

on:
  release:
    types: [published]

env:
  TARGET_PLATFORMS: "linux/amd64,linux/arm64/v8,linux/arm/v7"
  ALPINE_VERSION: latest
  GHCR_URL: ghcr.io
  PUSH_TO_DHCR: true
  PUSH_TO_GHCR: true
  PUSH_TO_AZCR: false


jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: latest
            install: true
            driver-opts: image=moby/buildkit:master
            use: true

      - name: Buildx Builder Create
        run: |
          docker buildx create --platform "${{ env.TARGET_PLATFORMS }}"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        if: ${{ env.PUSH_TO_DHCR }} != "false"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ env.PUSH_TO_GHCR }} != "false"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
            ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{raw}}

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        env:
          NO_DOCS: ${{ matrix.no_docs }}
        with:
          context: .
          file: ./Dockerfile
          labels: |
            "com.keplerdev.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.image.sha": ${{ github.sha }}
            "com.keplerdev.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.registry.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_IMAGE=latest
            USER=jessenich
            NO_DOCS=false
          platforms: ${{ env.TARGET_PLATFORMS }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build & Push Latest No Docs
        uses: docker/build-push-action@v2
        env:
          NO_DOCS: ${{ matrix.no_docs }}
        with:
          context: .
          file: ./Dockerfile
          labels: |
            "maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.maintainer: Jesse N. <jesse@keplerdev.com>"
            "com.keplerdev.image.sha": ${{ github.sha }}
            "com.keplerdev.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.registry.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            ALPINE_IMAGE=latest
            USER=jessenich
            NO_DOCS=true
          platforms: ${{ env.TARGET_PLATFORMS }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
