name: "Push Docker Image"

on:
  push:
    tags:
      - "v*"

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
  GHCR_URL: ghcr.io
  GHCR_LIBRARY: jessenich
  GHCR_REPO: alpine
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: alpine
  LABELS: maintainer=Jesse N. <jesse@keplerdev.com>

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine-version: [ 3.13, 3.14 ]


    name: Build Alpine Version ${{ matrix.alpine-version }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: latest
            install: true
            driver-opts: image=moby/buildkit:master
            use: true

      - name: Buildx Builder Create
        run: |
          docker buildx create \
            --platform "${{ env.TARGET_PLATFORMS }}" \
            --name "github-runner-builder" \
            --use

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          labels: |
            "${{ env.LABELS }}"
          images: |
            "${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}"
            "ghcr.io/${{ env.GHCR_LIBRARY }}/${{ env.GHCR_REPO }}"
          tags: |
            type=raw,enable=${{ contains(matrix.alpine-version, '3.14') }},priority=100,value=latest
            type=semver,enable=${{ startsWith(github.ref, 'refs/tags/') }},pattern={{major}}.{{minor}}.{{patch}},suffix=-alpine.${{ matrix.alpine-version }}
            type=semver,enable=${{ startsWith(github.ref, 'refs/tags/') }},pattern={{major}}.{{minor}},suffix=-alpine.${{ matrix.alpine-version }}

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        env:
          platforms: "${{ env.TARGET_PLATFORMS }}"
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VARIANT=${{ matrix.alpine-version }}
            NON_ROOT_ADMIN=sysadm
            TZ=UTC
          platforms: "${{ env.platforms }}"
          pull: true
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
